/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PowerUsageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addRecord"
      | "getRecordMetadata"
      | "getRecordUsage"
      | "getTotalRecords"
      | "getUserRecordByIndex"
      | "getUserRecordCount"
      | "getUserRecords"
      | "protocolId"
      | "recordExists"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "PowerRecordAdded" | "PowerRecordRetrieved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addRecord",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordMetadata",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordUsage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalRecords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRecordByIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRecordCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRecords",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordExists",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addRecord", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecordMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordUsage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRecordByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordExists",
    data: BytesLike
  ): Result;
}

export namespace PowerRecordAddedEvent {
  export type InputTuple = [
    recordId: BigNumberish,
    owner: AddressLike,
    timestamp: BigNumberish,
    period: BigNumberish
  ];
  export type OutputTuple = [
    recordId: bigint,
    owner: string,
    timestamp: bigint,
    period: bigint
  ];
  export interface OutputObject {
    recordId: bigint;
    owner: string;
    timestamp: bigint;
    period: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PowerRecordRetrievedEvent {
  export type InputTuple = [recordId: BigNumberish, requester: AddressLike];
  export type OutputTuple = [recordId: bigint, requester: string];
  export interface OutputObject {
    recordId: bigint;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PowerUsage extends BaseContract {
  connect(runner?: ContractRunner | null): PowerUsage;
  waitForDeployment(): Promise<this>;

  interface: PowerUsageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRecord: TypedContractMethod<
    [
      encryptedUsageInput: BytesLike,
      inputProof: BytesLike,
      period: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getRecordMetadata: TypedContractMethod<
    [recordId: BigNumberish],
    [
      [string, bigint, bigint] & {
        owner: string;
        timestamp: bigint;
        period: bigint;
      }
    ],
    "view"
  >;

  getRecordUsage: TypedContractMethod<
    [recordId: BigNumberish],
    [string],
    "view"
  >;

  getTotalRecords: TypedContractMethod<[], [bigint], "view">;

  getUserRecordByIndex: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  getUserRecordCount: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  getUserRecords: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  recordExists: TypedContractMethod<
    [recordId: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRecord"
  ): TypedContractMethod<
    [
      encryptedUsageInput: BytesLike,
      inputProof: BytesLike,
      period: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRecordMetadata"
  ): TypedContractMethod<
    [recordId: BigNumberish],
    [
      [string, bigint, bigint] & {
        owner: string;
        timestamp: bigint;
        period: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecordUsage"
  ): TypedContractMethod<[recordId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalRecords"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserRecordByIndex"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserRecordCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserRecords"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordExists"
  ): TypedContractMethod<[recordId: BigNumberish], [boolean], "view">;

  getEvent(
    key: "PowerRecordAdded"
  ): TypedContractEvent<
    PowerRecordAddedEvent.InputTuple,
    PowerRecordAddedEvent.OutputTuple,
    PowerRecordAddedEvent.OutputObject
  >;
  getEvent(
    key: "PowerRecordRetrieved"
  ): TypedContractEvent<
    PowerRecordRetrievedEvent.InputTuple,
    PowerRecordRetrievedEvent.OutputTuple,
    PowerRecordRetrievedEvent.OutputObject
  >;

  filters: {
    "PowerRecordAdded(uint256,address,uint256,uint256)": TypedContractEvent<
      PowerRecordAddedEvent.InputTuple,
      PowerRecordAddedEvent.OutputTuple,
      PowerRecordAddedEvent.OutputObject
    >;
    PowerRecordAdded: TypedContractEvent<
      PowerRecordAddedEvent.InputTuple,
      PowerRecordAddedEvent.OutputTuple,
      PowerRecordAddedEvent.OutputObject
    >;

    "PowerRecordRetrieved(uint256,address)": TypedContractEvent<
      PowerRecordRetrievedEvent.InputTuple,
      PowerRecordRetrievedEvent.OutputTuple,
      PowerRecordRetrievedEvent.OutputObject
    >;
    PowerRecordRetrieved: TypedContractEvent<
      PowerRecordRetrievedEvent.InputTuple,
      PowerRecordRetrievedEvent.OutputTuple,
      PowerRecordRetrievedEvent.OutputObject
    >;
  };
}
